version: '3'
services:
    mysql:
        image: mysql:8.0
        restart: always
        container_name: mysql
        ports:
            - "3306:3306" # 컨테이너 외부:컨테이너 내부
        environment:
            MYSQL_ROOT_PASSWORD:
            TZ: Asia/Seoul
        command:
            - --character-set-server=utf8mb4
            - --collation-server=utf8mb4_unicode_ci
        volumes:
            - /home/mysql:/var/lib/mysql # 호스트 경로:컨테이너 경로
    spring:
        image: prom:0.0.1-SNAPSHOT
        container_name: spring
        restart: always
        depends_on:
            - mysql
        ports:
            - "8080:8080"
        volumes:
            - /home/spring:/prom # 호스트 경로:컨테이너 경로