# prevent hangul broken
server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      force-response: true

spring:
  datasource:
    hikari:
      pool-name: hikari-pool
      connection-timeout: 10000
      validation-timeout: 10000
      maximum-pool-size: 20
      minimum-idle: 5
  jpa:
    database-platform: org.hibernate.dialect.MySQL57Dialect
    properties:
      hibernate:
        show_sql: true
        format_sql: true

mybatis:
  mapper-locations: classpath*:mapper/*.xml
  typeAliasesPackage: com.cgram.prom
  configuration:
    mapUnderscoreToCamelCase: true