# prevent hangul broken
server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      force-response: true

spring:
  datasource:
    driverClassName: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/{database}?serverTimezone=Asia/Seoul&verifyServerCertificate=false&useSSL=true
    username:
    password:
    hikari:
      pool-name: hikari-pool
      connection-timeout: 10000
      validation-timeout: 10000
      maximum-pool-size: 20
      minimum-idle: 5
  jpa:
    database-platform: org.hibernate.dialect.MySQL57Dialect
    hibernate:
      ddlAuto: validate
    properties:
      hibernate:
        show_sql: true
        format_sql: true
  servlet:
    multipart:
      max-file-size: 15MB
      max-request-size: 15MB

mybatis:
  mapper-locations: classpath*:mapper/*.xml
  typeAliasesPackage: com.cgram.prom
  configuration:
    mapUnderscoreToCamelCase: true

letter:
  mail:
    host: smtp.gmail.com
    port: 587
    id:
    pwd:

ncloud:
  api:
    accessKeyId:
    secretAccessKey:

jwt:
  private.key: classpath:private_key.pem
  public.key: classpath:public_key.pem
  secret-key:

image:
  directory: