# prevent hangul broken
server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      force-response: true

spring:
  datasource:
    hikari:
      pool-name: hikari-pool
      connection-timeout: 10000
      validation-timeout: 10000
      maximum-pool-size: 20
      minimum-idle: 5
      data-source-properties:
        rewriteBatchedStatements: true
  jpa:
    database-platform: org.hibernate.dialect.MySQL57Dialect
    defer-datasource-initialization: true
    properties:
      hibernate:
        show_sql: true
        format_sql: true

mybatis:
  typeAliasesPackage: com.cgram.prom
  configuration:
    multipleResultSetsEnabled: false
    mapUnderscoreToCamelCase: true
    callSettersOnNulls: true
    jdbcTypeForNull: null